// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxBs98Ir2sj4AwFmb3LAbVsybMqe2pfw0',
    appId: '1:134064593405:web:f2757f05c77c149e51e194',
    messagingSenderId: '134064593405',
    projectId: 'authentication-firebase-434e5',
    authDomain: 'authentication-firebase-434e5.firebaseapp.com',
    storageBucket: 'authentication-firebase-434e5.appspot.com',
    measurementId: 'G-XEJ2W76E5K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo2eUQKCk_W7veG1nZG7p8OuMoAbfBDZQ',
    appId: '1:134064593405:android:35f7f4302c4ed70151e194',
    messagingSenderId: '134064593405',
    projectId: 'authentication-firebase-434e5',
    storageBucket: 'authentication-firebase-434e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiM_i5OMElA5-UnSBYM1azKHc6et33Llw',
    appId: '1:134064593405:ios:e18eb7c67b5b04e351e194',
    messagingSenderId: '134064593405',
    projectId: 'authentication-firebase-434e5',
    storageBucket: 'authentication-firebase-434e5.appspot.com',
    androidClientId: '134064593405-teodid0esh7d9r4loha2jt1v9ife4o28.apps.googleusercontent.com',
    iosClientId: '134064593405-b630ujpv61r3d29opvav54072adjgie4.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseMessaging',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiM_i5OMElA5-UnSBYM1azKHc6et33Llw',
    appId: '1:134064593405:ios:286d0a397466f49351e194',
    messagingSenderId: '134064593405',
    projectId: 'authentication-firebase-434e5',
    storageBucket: 'authentication-firebase-434e5.appspot.com',
    androidClientId: '134064593405-teodid0esh7d9r4loha2jt1v9ife4o28.apps.googleusercontent.com',
    iosClientId: '134064593405-blekstcc7qt5trtjq8mt33b0odmlhpus.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseMessaging.RunnerTests',
  );
}
