// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsv-8xbyk7ZLGscTDvgVJhwKXXQS6F62U',
    appId: '1:1034158875528:web:f97bee0e2850879f58d03d',
    messagingSenderId: '1034158875528',
    projectId: 'crud-operation-cloud-firestore',
    authDomain: 'crud-operation-cloud-firestore.firebaseapp.com',
    storageBucket: 'crud-operation-cloud-firestore.appspot.com',
    measurementId: 'G-V0SMZ5LCG1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwMkM3MTSusXT_UVqYyTb1bo_2ianfDWY',
    appId: '1:1034158875528:android:e81bc7652e05c6bb58d03d',
    messagingSenderId: '1034158875528',
    projectId: 'crud-operation-cloud-firestore',
    storageBucket: 'crud-operation-cloud-firestore.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDRNUS6NAN8Rs4pxn0StEecyIlpS2aOJU',
    appId: '1:1034158875528:ios:f9b25d6126fa79e258d03d',
    messagingSenderId: '1034158875528',
    projectId: 'crud-operation-cloud-firestore',
    storageBucket: 'crud-operation-cloud-firestore.appspot.com',
    iosBundleId: 'com.example.firebaseMessaging',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDRNUS6NAN8Rs4pxn0StEecyIlpS2aOJU',
    appId: '1:1034158875528:ios:6efbc6e4e1e33f6458d03d',
    messagingSenderId: '1034158875528',
    projectId: 'crud-operation-cloud-firestore',
    storageBucket: 'crud-operation-cloud-firestore.appspot.com',
    iosBundleId: 'com.example.firebaseMessaging.RunnerTests',
  );
}
